export const SET_AlERT = "SET_AlERT";
export const REMOVE_AlERT = "REMOVE_AlERT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
